beyondchaos_windows.zip: beyondchaos_ex.exe README custom/**/*
	zip -r beyondchaos_windows.zip beyondchaos_ex.exe README custom
beyondchaos_ex.exe: *.py data/**/* tables/* custom/**/*
	pyinstaller gui.py -F -n beyondchaos_ex --add-data tables;tables --add-data custom;custom --add-data data;data
	mv -f dist\beyondchaos_ex.exe .